# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

meshConfig:
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  # This is derived from the default access log format: https://istio.io/latest/docs/tasks/observability/logs/access-log/#default-access-log-format
  accessLogFormat: |
    {
      "protocol": "%PROTOCOL%",
      "upstream_service_time": "%REQ(x-envoy-upstream-service-time)%",
      "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
      "duration": "%DURATION%",
      "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
      "route_name": "%ROUTE_NAME%",
      "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
      "user_agent": "%REQ(USER-AGENT)%",
      "response_code": "%RESPONSE_CODE%",
      "response_flags": "%RESPONSE_FLAGS%",
      "start_time": "%START_TIME%",
      "method": "%REQ(:METHOD)%",
      "request_id": "%REQ(X-REQUEST-ID)%",
      "upstream_host": "%UPSTREAM_HOST%",
      "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
      "client_ip": "%REQ(True-Client-Ip)%",
      "requested_server_name": "%REQUESTED_SERVER_NAME%",
      "bytes_received": "%BYTES_RECEIVED%",
      "bytes_sent": "%BYTES_SENT%",
      "upstream_cluster": "%UPSTREAM_CLUSTER%",
      "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
      "authority": "%REQ(:AUTHORITY)%",
      "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
      "response_code_details": "%RESPONSE_CODE_DETAILS%"
    }
  pathNormalization:
    normalization: MERGE_SLASHES
  defaultConfig:
    holdApplicationUntilProxyStarts: true
    gatewayTopology:
      forwardClientCertDetails: SANITIZE
  extensionProviders:
    - name: "authservice"
      envoyExtAuthzGrpc:
        service: "authservice.authservice.svc.cluster.local"
        port: "10003"

pilot:
  env:
    PILOT_JWT_ENABLE_REMOTE_JWKS: hybrid
